Add an option to turn off branching in DMC batched driver
QMCPACK/qmcpack pull request #2752
Opened 2020-10-13 23:20 UTC by ye-luo

## Proposed changes
Mostly needed for benchmark purpose.
`<parameter name="branching"> no </parameter>` to turn off branching.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2020-10-14 12:34 UTC, prckent requested changes
This is a dangerous developer/debug only option and should be labeled as such, e.g. "debug_disable_branching" (notice I flipped the meaning yes/no). It should also go in the documentation so that the documentation remains a faithful description of working input.

2020-10-15 04:03 UTC, ye-luo commented
Use string type for the flag at the moment. Due to #2758.
@Hyeondeok-Shin has started consolidating the input handling at the bottom level.

2020-10-15 15:30 UTC, prckent approved these changes

2020-10-15 15:31 UTC, merged

2020-10-15 15:37 UTC, ye-luo commented
We will need a "no branching DMC" feature with correct energy implemented but it is different from "debug_disable_branching".