Two-body jastrow optimization bug fix : Set opt offset to be equal to first active variable
QMCPACK/qmcpack pull request #2834
Opened 2021-01-01 19:44 UTC by shivupa

Detailed disussion on issue #2814

## Proposed changes
The two body jastrow optimization would fail when the first optimizable parameters were not the first parameters (e.g. if the u-u terms were frozen). This implements @markdewing's suggestions from #2814, which fixes the offset variable to point at the correct set of parameters. 

Closes #2814 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
Laptop Intel i7-7700HQ
Desktop Intel i7-2600S

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-01-01 20:39 UTC, prckent commented
OK to test

2021-01-01 21:18 UTC, ye-luo requested changes
Unfortunately, the added change breaks optimization tests like short-H4-opt-linear-16-1 and short-H4-opt-OneShiftOnly-1-16.

2021-01-12 14:21 UTC, prckent commented
@shivupa Since this is more complicated than we were expecting, should I find someone else to continue this? I know you have your own research to get on with, and on our side this might be the catalyst to setup a broader set of quick to run deterministic optimization tests, check if this error pattern is repeated in other jastrows etc.. Cheers, Paul

2021-01-12 15:31 UTC, shivupa commented
Thanks. I tried to take a look, but it is definitely more complicated than I have the bandwidth for right now! I'd appreciate that.

2021-01-12 15:31 UTC, closed without merging