Fix SpinDensityNew HDF5 writing
QMCPACK/qmcpack pull request #2863
Opened 2021-01-29 15:51 UTC by PDoakORNL

## Proposed changes

Thanks to @jtkrogel for updating Nexus and his observations on the source and output this was pretty easy to fix.

HDF5 writing from EstimatorManagerNew is essentially unchanged from legacy until this PR. It assumes anything you'd write from an estimator is in the Data owned by the Manager in the various Cache blocks.  It isn't for the OperatorEstimators, this is now handled.

Several bugs involving zeroing the estimator data between blocks are fixed.

Regression involving asserts in Walker code necessitates commenting out test_WalkerControlMPI.cpp tests.

## What type(s) of changes does this code introduce?

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Leconte

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes Documentation has been added (if appropriate)

2021-02-02 06:13 UTC, ye-luo requested changes
better to merge #2866 first. Blocking merge for the moment.

2021-02-02 06:13 UTC, ye-luo commented on src/Estimators/EstimatorManagerNew.h
> +  void writeOperatorEstimators();
Need documentation.

2021-02-02 06:13 UTC, ye-luo commented on src/Estimators/OperatorEstBase.h
> +  void write();
Need documentation.

2021-02-08 17:48 UTC, PDoakORNL commented
I believe the requested changes are now done

2021-02-08 17:59 UTC, ye-luo approved these changes

2021-02-08 22:27 UTC, ye-luo commented
Test this please

2021-02-09 03:57 UTC, merged