Introduce multi walker shared resource to ParticleSet and Hamiltonian
QMCPACK/qmcpack pull request #2970
Opened 2021-02-28 14:12 UTC by ye-luo

## Proposed changes
This PR expands multi walker shared resource beyond TrialWaveFunction to cover ParticleSet and QMCHamiltonian
```
struct FatWalkerResourceCollection
{
  ResourceCollection pset_res;
  ResourceCollection twf_res;
  ResourceCollection ham_res;
}
```
The gold shared resources now are created in the driver. The driver level design is largely complete.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2021-02-28 16:15 UTC, prckent requested changes
Some initial comments, both required changes:
1. FatWalker -> ResourcedWalker (or other synonym)
2. The new .h for the above needs a description about what it does, plus function definition comments.

2021-02-28 16:21 UTC, ye-luo commented
> Some initial comments, both required changes:
> 
>     1. FatWalker -> ResourcedWalker (or other synonym)

This file only have resource related types right now but it is intended to provide driver based fat walker related types. For example, "WalkerElementsRef.h" will probably be fused into this file.

>     2. The new .h for the above needs a description about what it does, plus function definition comments.

Will do.

2021-03-01 21:43 UTC, ye-luo commented
@prckent Rename FatWalker to DriverWalker and add documentation to DriverWalkerTypes.h

2021-03-01 21:51 UTC, PDoakORNL commented
I'm reviewing now.

2021-03-01 23:39 UTC, PDoakORNL approved these changes
We have some issues with serialized walkers and resources to work out beyond this scope of this PR.  This looks good as a step forward for shared resource use for the straight forward batched case.

2021-03-01 23:50 UTC, ye-luo commented on src/QMCDrivers/QMCDriverNew.cpp
> +  if (dispatchers_.are_walkers_batched())
This is probably more of my own habit making bool return function names as questions instead of getter.

2021-03-02 01:17 UTC, prckent approved these changes
Thanks for addressing my review comments Ye.

2021-03-02 01:17 UTC, merged