[WIP] Move QMC_CLINE to CMake.
QMCPACK/qmcpack pull request #2981
Opened 2021-03-03 17:58 UTC by ye-luo

## Proposed changes
Set QMC_CLINE explicitly via CMake rather than depending on compiler defined macros.
The old code was fine when targeting only one architecture (CPU).
```C++
  #if defined(__AVX512F__)
    #define QMC_CLINE 64
  #else
    #define QMC_CLINE 32
  #endif
```

When OpenMP offload is used, the source code is compiled for two targets CPU and GPU.
```
int foo(Vector<float, aligned_allocator<float, QMC_CLINE>>)
{
  #pragma omp target
  { offload kernel }
}
```
The compiler transformed offload kernel carries C++ mangled function name foo with QMC_CLINE being part of it. For this reason, the caller (CPU pass) and the callee(GPU pass) doesn't match and kernels failed being loaded on GPU. https://bugs.llvm.org/show_bug.cgi?id=45401

WIP: I need more thinking because
1. "#pragma omp simd aligned(px)" needs to be changed to "aligned(px:QMC_CLINE)"
2. Default choice is 32 and machines with AVX512 needs to set it to 64. Do it in CMake allows to avoid changing 1.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2021-03-04 21:40 UTC, prckent requested changes
1. Please change QMC_CLINE to a self-describing and longer name. e.g. QMC_SIMD_ALIGNMENT. What CLINE means is not obvious.

2. Rename CheckSIMDAlignement.cmake ->CheckSIMDAlignment.cmake

2021-03-04 21:40 UTC, prckent commented on CMakeLists.txt
> +#---------------------------------------------------------------------------
Please add an example of the potential problem, as detailed in your PR text.

2021-03-05 14:35 UTC, prckent approved these changes
Thanks Ye!

2021-03-05 14:45 UTC, ye-luo commented
@prckent This should make the nightly test error on sulfur go away without need of passing "-march=skylake" as a workaround.

2021-03-05 16:17 UTC, merged

2021-03-06 02:08 UTC, prckent commented
Nightly scripts have been updated.