Improve XML error handling + Add success message
QMCPACK/qmcpack pull request #2991
Opened 2021-03-04 21:09 UTC by prckent

## Proposed changes

Quality of life improvements:
To ensure an actual error code is returned for bad XML, replace a historical few error calls with APP_ABORT. 
Also print "QMCPACK execution completed successfully" just prior to application return (if no errors/exceptions etc.). Check for this in ctests to catch all early exits.

## What type(s) of changes does this code introduce?

- Bugfix
- New feature
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

sulfur, nightly gcc10 configuration.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

2021-03-04 22:12 UTC, ye-luo requested changes
Could you point to or provide a reproducer? Not clear where the issue is precisely.

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/QMCAppBase.cpp
> +    APP_ABORT("QMCAppBase::pushDocument");
returning false is self-consistent. abort is handled outside. I could not agree with this change.

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
> +    APP_ABORT("QMCMain::execute. Input document does not contain valid objects");
Use myComm->barrier_and_abort()

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
> +          APP_ABORT("QMCMain::validateXML");
Use myComm->barrier_and_abort().

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
> +        APP_ABORT("QMCMain::validateXML")
Use myComm->barrier_and_abort() including the message sent to app_error.

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
> +    APP_ABORT("QMCMain::validateXML. Illegal input. Missing Hamiltonian.");
Please use Use myComm->barrier_and_abort().

2021-03-04 22:12 UTC, ye-luo commented on src/QMCApp/qmcapp.cpp
> +  std::cout << "QMCPACK execution completed successfully" << std::endl;
We cannot print on very rank.
Already out to the MPI scope. Very hard to have a consistent logic to send clean output.
Considering we'd better not using this for ctest check. Removal is better for me.

2021-03-04 22:43 UTC, prckent commented on CMake/macros.cmake
> +                PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully"
This only tightens the pass criterion (??)

2021-03-04 22:51 UTC, prckent commented
Reproducer: Delete the / on a closing XML tag with existing code. e.g. An easy user error such as <random seed="666">

On test criteria, which are only tightened here: see https://cmake.org/cmake/help/latest/prop_test/PASS_REGULAR_EXPRESSION.html and (say ) https://cmake.org/cmake/help/latest/prop_test/SKIP_RETURN_CODE.html . All the pass conditions have to be met and all the fail conditions have to not be met.

Will update the calls and arrange for node 0 only output.

We are going to print something (said in PI voice)

2021-03-04 23:00 UTC, ye-luo commented on CMake/macros.cmake
> +                PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully"
Tightening is good.

2021-03-04 23:01 UTC, ye-luo commented on src/QMCApp/qmcapp.cpp
> +  std::cout << "QMCPACK execution completed successfully" << std::endl;
Since this helps tightening the pass criteria, we should add this. Please pay attention to ensemble runs.

2021-03-05 00:40 UTC, prckent commented
Maybe fixed. Not sure about ensemble runs, did check conventional MPI runs.

2021-03-05 00:47 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
>      return false;
could you remove the return.

2021-03-05 00:47 UTC, ye-luo commented on src/QMCApp/QMCMain.cpp
> +        {
could you remove the {} around a single line if possible.

2021-03-05 00:47 UTC, ye-luo commented on src/QMCApp/qmcapp.cpp
>        qmc->execute();
This execute also returns true/false. Better to check.

2021-03-05 16:31 UTC, ye-luo submitted a review, later dismissed

2021-03-05 16:36 UTC, ye-luo submitted a review, later dismissed

2021-03-05 17:21 UTC, ye-luo approved these changes

2021-03-05 18:55 UTC, merged