PPCONVERT replace Blitz with multi
QMCPACK/qmcpack pull request #3009
Opened 2021-03-11 22:27 UTC by correaa

## Proposed changes

Replace Blitz dependency with Multi arrays

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-03-11 23:42 UTC, correaa commented
This PR is not ready. I marked it as WIP.

2021-03-16 00:22 UTC, correaa commented
Blitz is not a dependency anymore.

```
$ cmake -DBUILD_PPCONVERT=1 ../.. && make -j 10 ppconvert VERBOSE=1 && ctest -R ppconvert -VV
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QMC_SYMLINK_TEST_FILES = ON.  Using symbolic links for large test files may cause test failures if the build is installed on a separate filesystem from the source.
-- Found Python3: /usr/bin/python3.8 (found version "3.8.5") found components: Interpreter 
-- Unable to import PySCF python module. PySCF tests will not be run.
-- Did not find a patched Quantum ESPRESSO (QE) distribution with pw2qmcpack.x. QE tests will not be run.
-- CMAKE_BUILD_TYPE is RELEASE
-- defining the float point precision
   Base precision = double
   Full precision = double
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Trying to figure out .....
-- Compiler: GNU
-- libstdc++/C++ compiler version compatibility check pass
-- C++14 standard library supported
-- Setting QMC_SIMD_ALIGNMENT to 32
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: CXX 
-- Detected Open MPI. Setting bind-to options for thread affinity in MPIEXEC_PREFLAGS.
CMake Warning at CMakeLists.txt:507 (MESSAGE):
  Building MPI version without using MPI compiler wrappers.

  This may not build qmcpack correctly.  To ensure the correct version,
  specify the compiler wrappers to cmake.

  For example: cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++

  To build without MPI, pass '-DQMC_MPI=0' to cmake


-- MPI runner MPIEXEC_EXECUTABLE : /usr/bin/mpiexec
-- MPIEXEC_NUMPROC_FLAG : -n
-- MPIEXEC_PREFLAGS : --bind-to;none
-- Tests run as : /usr/bin/mpiexec -n NUM_PROCS --bind-to none EXECUTABLE
-- MPI is enabled
-- Trying to find LAPACK from Intel MKL
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- Intel MKL library files not found via FindLAPACK.
-- Trying to find alternative LAPACK libraries
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- LAPACK linker flags: 
-- LAPACK libraries: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- No usable vector math library detected.
-- SINCOS_INCLUDE : cmath
-- Performing Test HAVE_SINCOS
-- Performing Test HAVE_SINCOS - Success
-- FFTW_INCLUDE_DIR=/usr/include
-- FFTW_LIBRARIES=/usr/lib/x86_64-linux-gnu/libfftw3.so
-- Found FFTW
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.10") 
-- Linking dynamic HDF5 library
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.4") found components: C 
-- Parallel HDF5 library found
-- Using HDF5 parallel collective I/O code paths
-- Found Boost: /usr/include (found suitable version "1.71.0", minimum required is "1.61.0")  
-- Setting Boost_INCLUDE_DIRS=/usr/include
-- CUDA disabled
-- CUDA NVTX APIs disabled
-- VTune ittnotify APIs disabled
Project C_FLAGS:  -std=c99 -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Werror=vla -march=native -O3 -DNDEBUG -fomit-frame-pointer -ffast-math
Project CXX_FLAGS:  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -D__forceinline=inline -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -march=native -O3 -DNDEBUG -fomit-frame-pointer -ffast-math
Project INCLUDE_DIRECTORIES: /home/correaa/prj/qmcpack/src;/home/correaa/prj/qmcpack/build/gnu/src
Project EXE_LINKER_FLAGS:  
Project SHARED_LINKER_FLAGS:  
-- Ready to build qmcpack
sed supports -E
Git branch: ppconvert_multi
Git commit hash: 85cd48875970deb7060325f3dd1b62898bc147e5
-- Adding integration tests for QMCPACK
Set QMC_VERBOSE_CONFIGURATION=1 for details of which tests will be enabled.
Adding system tests for QMCPACK
Skipping converter tests with HDF output because h5diff was not found
Adding estimator tests for QMCPACK
Missing python module pandas, not adding test estimator-latdev
Missing python module pandas, not adding test estimator-latdev-free
Missing python module pandas, not adding test estimator-sofk
Adding I/O tests for QMCPACK
QMC_DATA is not set. Performance tests will be skipped.
Adding example tests for QMCPACK
Adding Nexus tests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/correaa/prj/qmcpack/build/gnu
/usr/bin/cmake -S/home/correaa/prj/qmcpack -B/home/correaa/prj/qmcpack/build/gnu --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 ppconvert
make[1]: Entering directory '/home/correaa/prj/qmcpack/build/gnu'
/usr/bin/cmake -S/home/correaa/prj/qmcpack -B/home/correaa/prj/qmcpack/build/gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/correaa/prj/qmcpack/build/gnu/CMakeFiles 3
make -f CMakeFiles/Makefile2 src/QMCTools/ppconvert/src/CMakeFiles/ppconvert.dir/all
make[2]: Entering directory '/home/correaa/prj/qmcpack/build/gnu'
make -f src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/build.make src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/depend
make[3]: Entering directory '/home/correaa/prj/qmcpack/build/gnu'
cd /home/correaa/prj/qmcpack/build/gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/correaa/prj/qmcpack /home/correaa/prj/qmcpack/src/QMCTools/ppconvert/src/common /home/correaa/prj/qmcpack/build/gnu /home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common /home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/DependInfo.cmake --color=
Dependee "/home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/DependInfo.cmake" is newer than depender "/home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/depend.internal".
Dependee "/home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/correaa/prj/qmcpack/build/gnu/src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/depend.internal".
Scanning dependencies of target common
make[3]: Leaving directory '/home/correaa/prj/qmcpack/build/gnu'
make -f src/QMCTools/ppconvert/src/common/CMakeFiles/ [...]

2021-03-16 17:43 UTC, prckent requested changes
Troubles building with clangdev. Maybe a missed commit?

```
[ 77%] Building CXX object src/QMCTools/ppconvert/src/common/CMakeFiles/common.dir/CoulombPot.cc.o
In file included from /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/CoulombPot.cc:16:
In file included from /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/CoulombPot.h:19:
In file included from /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/PotentialBase.h:19:
In file included from /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/IO.h:20:
In file included from /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/IOBase.h:26:
/home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/IOVar.h:197:19: error: no matching constructor for initialization of 'Range'
  return Write(v, Range(n, n));
                  ^     ~~~~
/home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/Blitz.h:121:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct Range{
       ^
/home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/Blitz.h:121:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
/home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/src/QMCTools/ppconvert/src/common/Blitz.h:121:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
1 error generated.
```

2021-03-16 17:45 UTC, prckent commented
Working with gcc 10.2.0 though (?)

2021-03-17 03:57 UTC, correaa commented
> Troubles building with clangdev. Maybe a missed commit?

It is a clang thing.

I was able to reproduce the problem with `CXX=clang++ CC=clang cmake -DBUILD_PPCONVERT=1 ../.. && make -j 10 ppconvert VERBOSE=1 && ctest -R ppconvert -VV`

2021-03-17 04:04 UTC, correaa commented
fixed.

Works with `CXX=clang++ CC=clang cmake -DBUILD_PPCONVERT=1 ../.. && make -j 10 ppconvert VERBOSE=1 && ctest -R ppconvert -VV`

tested with 

```
$ clang++ --version                                                                                                                                                                       1 ↵
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
and

```
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2021-03-17 16:06 UTC, prckent submitted a review, later dismissed
Working with llvm as well and gcc now, and can confirm that the tests are passing.

This is a big improvement, removing our Blitz dependency by making use of multi. I have been debating about whether more tests are warranted. However since this update rather elegantly replaces blitz with minimal changes to the ppconvert codes (at this point), and the existing oxygen conversion test would catch any major issues, I do not think that we need any more at this point.

Thanks @correaa  !

2021-03-17 19:57 UTC, correaa commented
> Working with llvm as well and gcc now, and can confirm that the tests are passing.
> Thanks @correaa !

Always happy to remove lines of code.

For reference Blitz is 
```
cd blitz && find . -name '*.[h|c]*' | xargs wc -l
77939
```
... lines of code.

Multi (not counting tests) is 
```
cd multi && find . -name '*.hpp' | xargs wc -l
21847
```
... LOC

Not counting the blas, cublas, cufft, fftw, cudart adaptors, is 7536 LOC.

BTW, I think tests are not passing now because of the pending issue of multi with AFQMC, which reminds me...

2021-03-20 00:23 UTC, correaa commented
This conflicts should be merged giving priority to the files in the develop branch (after merged https://github.com/QMCPACK/qmcpack/pull/3023)

2021-03-20 18:28 UTC, ye-luo approved these changes

2021-03-20 18:29 UTC, merged