Nexus: Add L2 generation functionality
QMCPACK/qmcpack pull request #3079
Opened 2021-04-07 16:48 UTC by mcbennet

## Proposed changes

The following PR adds L2 functionality to the GaussianPP class within pseudopotential.py.
These additions only expand the GuassianPP class and do not change any existing functionality.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-04-08 17:57 UTC, jtkrogel requested changes
@mcbennet after addressing the comments, please post here the output from nxs-test.

2021-04-08 17:57 UTC, jtkrogel commented on nexus/lib/pseudopotential.py
> +from testing import *
Remove testing import

2021-04-08 17:57 UTC, jtkrogel commented on nexus/lib/pseudopotential.py
> +    def append_to_component(self,l,coeff,expon,rpow):
Add a 1-2 sentence docstring very briefly describing what this function does.  If the role of this function is simply to be called by another, note that here along with the name of the other function.  Please do the same for the other functions below.

2021-04-09 04:05 UTC, mcbennet commented
> @mcbennet after addressing the comments, please post here the output from nxs-test.

The structure test is the only failure when I run nxs-test. Attached is the output of `nxs-test -R structure --verbose
[nxs_structure_test.txt](https://github.com/QMCPACK/qmcpack/files/6283094/nxs_structure_test.txt)
`

2021-04-09 12:09 UTC, jtkrogel commented
Please update line 1645 in test_structure.py to read `assert(testing.check_object_eq(res,ref,atol=1e-12))` and let me know if this fixes things.

2021-04-09 15:04 UTC, mcbennet commented
> Please update line 1645 in test_structure.py to read `assert(testing.check_object_eq(res,ref,atol=1e-12))` and let me know if this fixes things.

Thank you. The structure test now passes.

2021-04-09 15:32 UTC, jtkrogel approved these changes
LGTM

2021-04-09 17:10 UTC, ye-luo approved these changes

2021-04-09 18:10 UTC, prckent commented
OK to test

2021-04-09 19:53 UTC, merged