[WIP] Enable GPU CI on GitHub Actions self-hosted runner
QMCPACK/qmcpack pull request #3258
Opened 2021-06-25 15:10 UTC by williamfgc

## Proposed changes

- This PR enables GPU CI using legacy CUDA on deterministic tests running on sulfur as a self-hosted runner on GitHub Actions.
- Set new workflow configuration file to trigger with current on-demand workflow: "Test this please" as PR comment by authorized user. Currently the new status will only show up if triggered.
- Set LD_LIBRARY_PATH to point at CUDA runtime libraries

To verify/understand:
- [ ] YAML GitHub Actions structure and functionality
- [ ] Make sure PR status is reported as a check when triggered 
- [ ] Directory structure for jobs on sulfur as a self-hosted runner (currently enabled)
- [ ] Status state is correctly reported through `${{job.status}}`
- [ ] Only authorized users can trigger the workflow

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature (GPU CI test)
- Testing changes (new CI workflow to test with `-DQMC_CUDA=1` on self-hosted runner)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
sulfur locally, entire workflow must run on GitHub Actions

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-06-25 15:15 UTC, prckent commented
I don't like exposing ci-github-actions-self-hosted.yaml in this public repo. Can we move it somehow or put the more delicate parts in a private repo different from this one?

2021-06-25 15:20 UTC, prckent requested changes
Comments left above. Appropriately this is [WIP].

2021-06-25 17:17 UTC, williamfgc commented
Hi @prckent thanks for the feedback. As we discussed offline, we're using GitHub secrets to address your valid concern. Now we have a chicken-and-egg problem since this needs to be merged in order to be fully tested on CI with a "dummy" PR. Let me know if you other points to address.

2021-06-25 17:41 UTC, prckent submitted a review, later dismissed

2021-06-25 17:43 UTC, prckent commented
I added a mention of the precision in the legacy CUDA configure line as a reminder for future readers that the default precision is mixed and different from the CPU default.

Remove the [WIP]?

2021-06-25 17:43 UTC, williamfgc commented
@prckent please don't merge yet, I'm testing the conditional in another repo. This won't work as-is (among other things we'll find after merging).

2021-06-25 18:36 UTC, williamfgc commented
@prckent OK, removed the [WIP]. The conditional is enabled through GitHub Actions `env` variables, secrets are hidden from logs and those `env` variables are not used anywhere in the workflows. After merge more testing is needed.

2021-06-25 19:02 UTC, williamfgc commented
@ye-luo let me know if you have any feedback before merging and attempting to test the actual workflow. Thanks!

2021-06-25 19:05 UTC, ye-luo commented
Test this please

2021-06-29 02:03 UTC, prckent commented
The changes here are easily reversible if needed. @ye-luo OK to merge?

2021-06-29 02:07 UTC, ye-luo commented
I don't see a new entry after saying the magic word. @williamfgc is this expected to work?

2021-06-29 02:15 UTC, williamfgc commented
@ye-luo it should only be triggered if it's part of the `develop` branch, so a new PR won't change the expected behavior, from [docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment). Once merged we can do a dummy PR to test.

2021-06-29 02:33 UTC, ye-luo approved these changes

2021-06-29 02:33 UTC, merged