Debug build use consistent options.
QMCPACK/qmcpack pull request #3300
Opened 2021-07-20 00:14 UTC by ye-luo

## Proposed changes

A Debug build is intended to debug QMCPACK source code rather than a compiler option. For this reason, Debug build should carry compiler options as similar to Release build.
GNU/Clang -ffast-math and NVHPC -fast are applied to Debug build as well. So apply them direct to CMAKE_CXX_FLAGS

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2021-07-20 19:37 UTC, PDoakORNL requested changes
Default Debug build should have -fno-omit-frame-pointer

2021-07-20 19:37 UTC, PDoakORNL commented on CMake/ClangCompilers.cmake
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fomit-frame-pointer -ffast-math")
-fomit-frame-pointer is no good for debugging.
hence the split.

2021-07-20 19:50 UTC, prckent commented
Concurring with Peter on wanting (actually needing) the frame-pointer in the debug build.

2021-07-21 19:23 UTC, PDoakORNL approved these changes

2021-07-21 19:36 UTC, PDoakORNL commented
It's unclear to me that we have the best gcc and pgi debug flags but I think the exploration of that belongs in another PR.

2021-07-21 21:22 UTC, ye-luo commented
Start testing in-house

2021-07-21 22:58 UTC, merged