Use unique_ptr for QMCHamiltonian, TrialWaveFunction and MCWalkerConfiguration
QMCPACK/qmcpack pull request #3356
Opened 2021-08-13 13:40 UTC by quantumsteve

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This fixes memory leaks allocated by QMCHamiltonian::makeClone and TrialWaveFunction::makeClone. Following this pattern, I did the same for MCWalkerConfiguration.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

2021-08-13 19:23 UTC, quantumsteve commented on src/QMCDrivers/CloneManager.cpp
> -  HPoolClones[0]   = hampool;
objects for thread 0 are owned elsewhere and passed in while objects for other threads are cloned and therefore owning pointers.

I tried making just this change to the develop branch and get the same test failures.

2021-08-13 19:25 UTC, quantumsteve commented on src/QMCDrivers/CloneManager.cpp
> -  guideClones[0] = &guide;
similar pattern here.

2021-08-13 19:25 UTC, quantumsteve commented on src/QMCDrivers/CloneManager.cpp
> -    return;
similar pattern here

2021-08-24 18:31 UTC, quantumsteve commented
@ye-luo @prckent This is ready for review

2021-08-24 19:04 UTC, prckent reviewed
Happy to see the vestigial USE_PARTICLESET_CLONES gone

Slightly worried by some of the codecov lack of coverage warnings given the sensitivity of this code. It LGTM but would be good to hit with a test, particularly makeClones. Assuming that codecov is not confused, did you already try to build something @quantumsteve ? Suggestions @ye-luo , @PDoakORNL ?

2021-08-31 00:27 UTC, ye-luo requested changes
There seems only minor issues to be addressed before merging.

2021-08-31 00:27 UTC, ye-luo commented on src/QMCDrivers/WFOpt/CostFunctionCrowdData.cpp
> +    auto psiCopy = Psi.makeClone(*pCopy);
Prefer
```
p_ptr_list_[ib] = std::make_unique<ParticleSet>(P);
auto& pCopy = *p_ptr_list_[ib];
```
This avoid `pCopy` and move.

2021-08-31 00:27 UTC, ye-luo commented on src/QMCDrivers/CloneManager.cpp
> +      hClones[ip] = hClones_uptr[ip-1].get();
Format source code.

2021-08-31 00:27 UTC, ye-luo commented on src/QMCDrivers/CloneManager.h
>    ///walkers
Please add note for XXX_uptr pattern.
Describe XXX_uptr[N-1] and XXX[N] relation.

2021-08-31 16:45 UTC, ye-luo approved these changes

2021-08-31 17:34 UTC, ye-luo commented
Test this please

2021-08-31 18:35 UTC, merged