missing initialize in J1Spin
QMCPACK/qmcpack pull request #3595
Opened 2021-11-08 16:47 UTC by shivupa

## Proposed changes

This was missed in #3257. 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
AMD workstation 
## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-11-08 16:54 UTC, prckent commented
Test this please

2021-11-08 16:59 UTC, prckent submitted a review, later dismissed
LGTM, subject to CI.

Thanks Shiv! I am resisting commenting on the rest of this older code, which definitely needs some tidying. Clearly this is an improvement though.

2021-11-08 17:35 UTC, shivupa commented
Sure! I am open to cleaning stuff up and would appreciate any specific things that need addressed! Either in this or a separate PR.

2021-11-08 17:50 UTC, ye-luo requested changes
In the unit test, please add a call to this fixed constructor and call evaluateLog() to validate the results.

2021-11-08 23:14 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_J1Spin.cpp
> +  // Check clone constructor
Could you fuse this test into the above one?

2021-11-10 01:31 UTC, ye-luo approved these changes

2021-11-10 01:34 UTC, ye-luo commented
Test this please

2021-11-10 02:20 UTC, merged