Save and restore variational parameters to XML
QMCPACK/qmcpack pull request #3625
Opened 2021-11-22 21:57 UTC by markdewing

The first step towards a solution to save and restore all variational parameters (VP) as discussed in #3619

Reading from a VP file is not intended to create the list of variational parameters.  The usage model is that the variational parameters are set up as usual in the code, and then new values for those parameters are read in from the file.

This enables a workflow where some subset of parameters is optimized and then the wavefunction is enlarged (or the optimization of more parameters enabled) and further optimization is performed. Values that are not present in the VP file are not changed. Reading the VP file acts like an overlay of its values on the existing values read in from the wavefunction section.

The the list of values is contained under a "name_value_pairs" tag.  In the future one might want to store values differently, and that could be done under a different tag. For example, coefficients are often stored as Coeff_0, Coeff_1, etc. for a large number of values. It would take less space to store the prefix once and store all the values in an array.

XML is being used to get this capability started.  Eventually it will use HDF.

The XML file looks like this (from the unit test):
```
<?xml version="1.0"?>
<variational_parameters>
  <name_value_pairs>
    <vp>
      <name>s</name>
      <value>11234.6</value>
    </vp>
    <vp>
      <name>second</name>
      <value>0.000256789</value>
    </vp>
    <vp>
      <name>really_long_name</name>
      <value>-1.2</value>
    </vp>
  </name_value_pairs>
</variational_parameters>
```

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
laptop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2021-11-22 22:04 UTC, prckent commented
Maybe worth noting that other codes are already doing 10K parameter optimization, so the solution needs to be scalable. i.e. HDF5 as the preferred mode. But XML is certainly more human readable and possibly easier to debug.

2021-11-22 22:09 UTC, ye-luo requested changes
I think it will be better if we can first sort out how we would like the XML structure to look like. Could you arrange a discussion?

2021-11-22 22:15 UTC, markdewing commented
Can we have the discussion here?  Or do want it to have a separate issue?

2021-11-22 22:23 UTC, ye-luo commented
I was thinking of arranging a call. I feel there are more than this PR or #3619 to discuss before actually implementing anything. More generally, one key task is to define what VariableSet is. How to handle individual parameters, how to handle a set of related parameters. "How to handle 1k parameters I/O?" question starts from how VariableSet handles parameters. `coeff_0, coeff1, ...., coeff1k` is already a problem.

2021-11-22 22:28 UTC, prckent commented
If there needs to be much discussion, perhaps start with HDF5? Minimum viable product etc. This should be super simple - just dump a single array. I don't think we even need to be concerned with sets of parameters at this point, and I don't see many people using it initially. It will be immediately useful to have this capability, so nice to haves shouldn't delay us.

2021-11-22 22:32 UTC, ye-luo commented
> If there needs to be much discussion, perhaps start with HDF5? Minimum viable product etc. This should be super simple - just dump a single array. I don't think we even need to be concerned with sets of parameters at this point, and I don't see many people using parameter sets initially in any case. It will be immediately useful to have this capability, so nice to haves shouldn't delay us.

That looks like simple to implement and immediately useful. Only need dataset "all_parameters".

2021-11-22 22:39 UTC, markdewing commented
Regarding VariableSet - are you concerned about its scalability in memory?  It does store the string name for every parameter and uses a std::map to store the string name -> value mapping.  
Or do you have other concerns about the current VariableSet implementation?

2021-11-22 22:44 UTC, ye-luo commented
> Regarding VariableSet - are you concerned about its scalability in memory? It does store the string name for every parameter and uses a std::map to store the string name -> value mapping. Or do you have other concerns about the current VariableSet implementation?

`std::vector<pair_type> NameAndValue;` each pair contains a string and a value. Memory issue is real. In addition, there is a local VariableSet and global VariableSet, then 2x memory again. Third, this way of storing parameter, doing any computation needs to copy in and out to a array for numerical operation.

2021-12-03 19:27 UTC, markdewing commented
Will probably use only HDF for simplicity.

2021-12-03 19:27 UTC, closed without merging