Cache results from slow python script test_labels.py
QMCPACK/qmcpack pull request #3667
Opened 2021-12-15 22:30 UTC by quantumsteve

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Noticed that the python script test_labels.py is being rerun each time cmake is run. This caches the result in a unique variable

This is part of #2227. I hope we can further speed up generation of TEST_LABELS.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Refactoring (no functional changes, no api changes)
- Build related changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'

2021-12-15 23:02 UTC, ye-luo requested changes

2021-12-15 23:02 UTC, ye-luo commented on CMake/test_labels.cmake
> +  if (DEFINED ${TEST_NAME}_${QMC_CUDA}_${QMC_COMPLEX}_${QMC_MIXED_PRECISION})
`NOT DEFINED`?
Also please start with `TEST_LABELS_`
So `TEST_LABELS_${TEST_NAME}_${QMC_CUDA}_${QMC_COMPLEX}_${QMC_MIXED_PRECISION}`

2021-12-16 16:13 UTC, ye-luo commented
It will be more ugly if I do squash on github. Could you rebase and squash this PR?

2021-12-16 16:15 UTC, quantumsteve commented
> It will be more ugly if I do squash on github. Could you rebase and squash this PR?

done

2021-12-16 16:20 UTC, ye-luo approved these changes
Great. Second cmake only took 6 sec now on my workstation.

2021-12-16 17:43 UTC, ye-luo commented
Test this please

2021-12-16 20:16 UTC, merged