Remove twistnum in bspline SPO XML attribute
QMCPACK/qmcpack pull request #3792
Opened 2022-01-31 23:40 UTC by ye-luo

## Proposed changes
The existing documentation clearly says avoid using twistnum and I just made one more step by removing it.
Use twist="x.x y.y z.z" input to indicate the exact twist. From now on, all twistnum input will be ignored.
Massive changes are due to updating input files.
I explicit tested complex build.

## What type(s) of changes does this code introduce?
- Other (please describe): Simply input tags.

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2022-01-31 23:51 UTC, prckent commented
Lets imagine an old input file with twistnum but no twist specified in the XML. Do we abort?

2022-02-01 00:08 UTC, ye-luo commented
First if stopper is desired, I can add it but that requires updating nexus. Users must ensure matching nexus and QMCPACK. In the current way, mostly old input file works as intended with new QMCPACK.

In the massive updates of tests, I only saw two cases where I need to modify twist.
1. graphite performance test, the input was created probably a decade ago. twistnum=2 and I need to add twist="0 0 0.5".
2. All LiH-arb tests, I think you added the tests and the input file was manually created. Thus there was twistnum=0 without a twist specified. The code complains about not being able find the twist. In this case, I added twsit="-0.1 -0.2 -0.3".

In all the input files with a twist input, twistnum="-1" are already specified.

In brief, the only case that breaks is having twistnum input without twist input. The intended twist is not gamma but gamma does exist in the h5.

2022-02-01 00:24 UTC, prckent commented
Thanks. I was just asking the question. Safe option would be abort with a useful error if twistnum is specified and !=-1. A few minutes work on our part could avoid a bad surprise in future.

NEXUS is an easy update. Yes people should sync, no issues there. (@jtkrogel ?)

2022-02-01 14:40 UTC, jtkrogel commented
OK, first of all, I don't think `twistnum` should be removed.  I thought @ye-luo was going to open a separate issue on this for discussion.  There are two reasons for this:

1) Backwards compatibility.  Overall, I think we don't prioritize this enough and are overly willing to put users off just because "we don't like something".

2) Nexus is not a minor update and I have been postponing making this update because of the inverted sign issue, as documented in #1386.  

Instead, we should first make a PR to default use `twist` by default (and not require `twistnum="-1"` to be provided), and then if it is not provided, use `twistnum`.  Next, #1386 should be fixed in a PR, and we should be sure that HEG, Bspline, and LCAO wavefunctions are using the same convention.  Finally, Nexus should be updated in a PR to use the now correct and consistent definition of twists.  At this point, `twistnum` should remain an option for backwards compatibility reasons, but could be removed from the documentation with `twist` being promoted there instead.

2022-02-01 14:49 UTC, jtkrogel requested changes
#1386 and #3795 should be resolved first.

2022-02-01 22:24 UTC, ye-luo commented
My second thought on this. I think changing input precedence and keep old files running is better.
We need to remember twistnum has defect "twistnum is not robust against h5 file changes."

2022-02-01 22:26 UTC, ye-luo commented
If neither twistnum nor twist exist, is default to `twist=0 0 0` acceptable? The alterrnative is default twistnum=0 which I dislike.

2022-02-01 22:28 UTC, prckent commented
One possibility might be to print a warning ("This is potentially ambiguous. Specifying twist=xyz is preferred.") 

We could at least stop creating new files with twistnum.

2022-02-01 22:58 UTC, lshulen commented
I prefer requiring either twist or twistnum exist to having a default behavior.

2022-02-02 03:59 UTC, ye-luo commented
See  #3799

2022-02-02 03:59 UTC, closed without merging