Prepare MSD for offload
QMCPACK/qmcpack pull request #3900
Opened 2022-03-10 04:32 UTC by ye-luo

## Proposed changes
After sorting all the unique determinants, we can dispatch the computation by excitation level.
Before offloading to GPU, we make more functions static (callable inside kernel).
@TApplencourt made the initial change.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2022-03-10 16:21 UTC, anbenali submitted a review, later dismissed

2022-03-11 01:02 UTC, prckent requested changes
If the coverage was not confused, we seem to be missing a unit and perhaps deterministic integration test that hits mw_updateRatios_generic. This will only be called if the CI has high enough excitations. Given the upcoming offload work this would be good to add.

2022-03-11 05:45 UTC, ye-luo commented
> If the coverage was not confused, we seem to be missing a unit and perhaps deterministic integration test that hits mw_updateRatios_generic. This will only be called if the CI has high enough excitations. Given the upcoming offload work this would be good to add.

I expanded the unit tests to cover all the lower level functions called by mw_updateRatios_generic in `SmallMatrixDetCalculator.h`. I also tested rerouting mw_updateRatios to mw_updateRatios_generic.
It is not easy to construct a unit test for `mw_updateRatios_generic` which requires to instantiate a full MultiDirectDeterminant class with `>5` excitation. We currently relies on MultiSlaterDeterminant unit test to cover MultiDirectDeterminant and indeed need a direct unit test of MultiDirectDeterminant. Once I figure out that, I should have known how to construct a class with high excitation. So I won't add such unit tests in this PR.

mw_updateRatios_generic needs to run on the host because it servers arbitrary matrix sizes.
Consider it is a rare case, we won't offload it.

2022-03-11 05:46 UTC, ye-luo commented
Test this please

2022-03-11 15:49 UTC, prckent commented
Thanks Ye. Will merge after reading the response from @anbenali : I think we  need to hand construct a wavefunction with high excitations &/or add a FCI wavefunction, which will can trivially have all the excitations we would like even for a low electron count system. Have you tried to make one?

2022-03-11 18:54 UTC, anbenali commented
@prckent: We might need to increase the max excitation level in the future, but for now I do not know if it is needed. We can definitely produce one. given the effort needed for that, I would prefer to not block the merger of this PR until we get the unit tests updated for all this sections

2022-03-11 18:54 UTC, anbenali approved these changes

2022-03-11 19:21 UTC, prckent commented
@anbenali I am not going to slow down this PR, but I am making it a hard requirement that we hit that code path. Please think about generating a test. I expect at least a deterministic test. FCI on a pseudized atom in a large enough basis would do it. A unit test would be preferred. It would be prudent to PR this test ahead of offload code.

2022-03-11 19:26 UTC, prckent approved these changes

2022-03-11 19:26 UTC, merged