Fix slab (ppn)
QMCPACK/qmcpack pull request #4052
Opened 2022-06-08 04:50 UTC by ye-luo

## Proposed changes

Fixes #4051. Breakage happened in #3852 785ce12
In a slab calculation (ppn) with 3d ewald, `lattice.SuperCellEnum == SUPERCELL_SLAB` is true which cannot be used to select quasi2D code paths. Introduce `LRCoulombSingleton::isQuasi2D()` for this purpose.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

2022-06-08 14:33 UTC, PDoakORNL submitted a review, later dismissed
This looks clean to me.  @ye-luo if you want to wait on @Paul-St-Young please indicate.

2022-06-08 14:41 UTC, prckent requested changes
Please add a test with an appropriate expect fail for combinations such as npp that are not supported, and tweak the docs https://qmcpack.readthedocs.io/en/develop/simulationcell.html?highlight=bconds "Examples of valid include" -> "The only supported combinations are:"

2022-06-08 18:22 UTC, Paul-St-Young submitted a review, later dismissed

2022-06-08 18:29 UTC, Paul-St-Young commented
I agree this PR cleanly restores the 3D behavior before #3852

Although, I'm not sure if it's beneficial to include the k-space sum along z.
This sum calculates the interaction between this slab and its images in the z direction.
Presumably, this is the superfluous interaction one wants to remove using the `vacuum` option anyway.

@Hyeondeok-Shin 
Does an extrapolation of the ion-ion energy towards the `vacuum->\infty` limit come close to the "no z-sum" value?

2022-06-08 18:51 UTC, ye-luo commented
@Paul-St-Young to use `opt_breakup` with `p p n`, including the k-space sum along z is needed. I think `ewald_quasi2d` doesn't need it.

2022-06-08 18:54 UTC, ye-luo commented
Test this please

2022-06-08 22:36 UTC, merged

2022-06-09 01:16 UTC, Hyeondeok-Shin commented
@Paul-St-Young I didn't have a chance to do extrapolation because vacuum option didn't change ion-ion energy.