Expand C-graphite test walker counts with different cell sizes
QMCPACK/qmcpack pull request #4116
Opened 2022-07-14 20:24 UTC by Hyeondeok-Shin

## Proposed changes

Close #4081. 
This PR is to expand C-graphite performance test walker counts with different cell sizes.
Test for cell size e144, e64, e16 are added for C-graphite.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

2022-07-14 23:13 UTC, prckent requested changes
I think that QMC_C_MAX_SIZE and QMC_NIO_MAX_SIZE should be mentioned in our docs. The latter is overdue. Find a spot somewhere around https://qmcpack.readthedocs.io/en/develop/installation.html#performance-tests

2022-07-21 14:06 UTC, prckent submitted a review, later dismissed
Many thanks Hyeondeok.

LGTM.

I have updated the scripts for the nightlies on sulfur and nitrogen locally. We can check the results on cdash tomorrow and see if all is in order. Once we are satisfied, please add an entry to the manual.

2022-07-21 14:07 UTC, prckent commented
Test this please

2022-07-21 14:20 UTC, ye-luo commented on tests/performance/NiO/CMakeLists.txt
> +  if(QMC_PERFORMANCE_NIO_MAX_ATOMS)
Could you add a trap.
```
if(QMC_NIO_MAX_SIZE)
  message(FATAL_ERROR "Variable QMC_NIO_MAX_SIZE has been renamed to QMC_PERFORMANCE_NIO_MAX_ATOMS")
endif()

2022-07-21 15:04 UTC, prckent commented
Test this please

2022-07-21 18:45 UTC, prckent commented
@ye-luo OK?

2022-07-21 18:55 UTC, ye-luo approved these changes
LGTM

2022-07-21 18:55 UTC, merged