Add restart capability to batch driver
QMCPACK/qmcpack pull request #4125
Opened 2022-07-20 15:54 UTC by quantumsteve

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes
- Other (please describe):

### Does this introduce a breaking change?

- Yes
- No

## What systems has this change been tested on?

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

2022-07-20 16:46 UTC, PDoakORNL requested changes
This is work in progress but this is some information that I think its mostly on me for not have documented better in the class declarations.

2022-07-21 03:11 UTC, ye-luo commented
Test this please

2022-07-21 03:25 UTC, ye-luo commented on src/QMCDrivers/QMCDriverNew.cpp
> +  population_.saveWalkerConfigurations();
setWalkerOffsets is still needed. I put it static but Its moved to MCPopulation is likely temporary.

2022-07-21 03:25 UTC, ye-luo approved these changes

2022-07-21 04:58 UTC, ye-luo commented
Test this please

2022-07-21 13:47 UTC, PDoakORNL approved these changes

2022-07-21 13:48 UTC, PDoakORNL commented on src/QMCDrivers/QMCDriverNew.cpp
> +  population_.saveWalkerConfigurations();
Still a good incremental step.

2022-07-21 13:51 UTC, ye-luo approved these changes

2022-07-21 13:51 UTC, merged