Compute logarithm of rotation matrix
QMCPACK/qmcpack pull request #4131
Opened 2022-07-26 16:28 UTC by markdewing

Add functions to compute the matrix log of a rotation matrix and extract the entries of the resulting antisymmetric matrix to a list of parameters.

This should allow us to recover rotation parameters from a rotation matrix.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

2022-07-26 19:25 UTC, prckent commented
Mark - the code cov browser is timing out for me currently, but would it be reasonable to get the coverage a bit higher?

2022-07-26 19:43 UTC, markdewing commented
I'll have to look at the report when it's available, because I don't see how it's easily possible to increase the coverage. The only code that isn't hit are error checks (check for info after the call to geev and a check for a large imaginary part in the last loop).  And I'm not sure how to make those trigger.  Probably have to input a matrix that's not a rotation matrix.

I've run the round trip test over a grid of values. But that's the kind of test to run once, not as part of the unit tests that get run every time.

2022-07-26 20:01 UTC, prckent commented
Test this please

2022-07-27 17:33 UTC, PDoakORNL requested changes
Basically good to go.  Just fix the error handling move a little documentation.

2022-07-27 17:33 UTC, PDoakORNL commented on src/QMCWaveFunctions/RotatedSPOs.cpp
> +  // Assumes rot_mat is of the correct size and initialized to zero upon entry
Document these assumptions in the method declaration documentation.

2022-07-28 13:22 UTC, PDoakORNL approved these changes

2022-07-28 13:52 UTC, ye-luo commented
Test this please

2022-07-28 15:56 UTC, merged