Directly set c++17 for nvcc.
QMCPACK/qmcpack pull request #4247
Opened 2022-09-19 21:34 UTC by ye-luo

## Proposed changes
Current clang develop caused nvcc detection failure in CMake. Explicitly instructing the C++ standard used by nvcc works around the issue. See discussion in https://gitlab.kitware.com/cmake/cmake/-/issues/23971

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2022-09-19 21:36 UTC, prckent requested changes
Please link the Kitware discussion. Also a mention of the affected versions would be ideal, assuming we know what they are.

2022-09-19 21:40 UTC, ye-luo commented
Test this please

2022-09-19 21:42 UTC, ye-luo commented
> Please link the Kitware discussion. Also a mention of the affected versions would be ideal, assuming we know what they are.

Kitware gitlab issue link was provided. All CMake versions that QMCPACK supports are affected. The issue shows up with clang since Sep 08 nightly compiler. icpx+nvcc also potentially has this issue.

2022-09-20 00:01 UTC, prckent approved these changes

2022-09-20 00:02 UTC, prckent commented
I was thinking that more explanation in the actual cmake file would help, not here.

2022-09-20 00:11 UTC, ye-luo commented
Test this please

2022-09-20 01:36 UTC, merged