Protect try_run in CMake when cross compiling.
QMCPACK/qmcpack pull request #4601
Opened 2023-05-11 19:10 UTC by ye-luo

## Proposed changes
CrayLinuxEnvironment is considered cross-compiling. Thus try_run requires user input and stop.
Consider ppconvert is not critical, simply turn it off by default.
QMC_ISNAN option can be used to override the detection.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Frontier/Crusher

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

2023-05-11 19:18 UTC, ye-luo commented
Test this please

2023-05-12 12:11 UTC, prckent requested changes
QMC_ISNAN -> QMC_ENABLE_ISNAN or QMC_USE_ISNAN

I think either or the above would be clearer.

Add to docs.

2023-05-15 21:09 UTC, ye-luo commented
A second thought on the name of the cmake option. QMC_USE_ISNAN is reserved for a global option. Here, there is special customization for ppconvert and thus introduce `ENABLE_PPCONVERT` with docs added.

2023-05-16 15:05 UTC, prckent approved these changes
LGTM

2023-05-16 15:05 UTC, prckent commented
Test this please

2023-05-16 15:07 UTC, prckent commented
Test this please

2023-05-16 17:26 UTC, merged