Use simplices in convex_hull
QMCPACK/qmcpack pull request #4671
Opened 2023-07-12 15:08 UTC by prckent

## Proposed changes

Closes #4670 

This looks to be a trivial fix ; vertices was deprecated in scipy 1.11.0 https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#expired-deprecations . However I did not yet find the version when simplices was introduced - is it old enough?

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

sulfur, nightly config

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

2023-07-12 18:30 UTC, prckent commented
Test this please

2023-07-12 18:35 UTC, jtkrogel requested changes

2023-07-12 19:07 UTC, prckent commented on nexus/lib/numerics.py
> +            v = tri.simplices[ni]
Done

2023-07-12 19:45 UTC, prckent commented
Test this please

2023-07-12 19:46 UTC, prckent commented
Test this please

2023-07-12 21:20 UTC, markdewing commented
It looks like "simplices" was added in scipy 0.12 (released in 2013)

2023-07-12 21:37 UTC, markdewing approved these changes

2023-07-13 17:00 UTC, markdewing commented
test this please

2023-07-13 21:13 UTC, merged