Add traits for STO cartesian LCAO basis type
QMCPACK/qmcpack pull request #4833
Opened 2023-11-13 19:25 UTC by markdewing

Previously would silently always create STO's with spherical angular part.  The inconsistent wavefunction construction would lead to bad results for the energy (could get lower than true ground state energy during optimization.)

I don't know if this combination makes sense scientifically or computationally, but if not, there should be an error message.   Note that this combination can also be reached using STO's by specifying 'transform="yes"'. (That's what lead me to find the issue - a difference between the results of transform and no transform).

Add basic test to create the different types of LCAO basis sets.  It doesn't actually check that the results are constructed as desired. For now, this can be checked by looking at the printed output of the test.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

2023-11-13 23:11 UTC, ye-luo commented
Do we have a test case of STO, Cartesian, transform="no"? If there is one, we should expand it to cover transform=yes case.

2023-11-14 04:59 UTC, markdewing commented
Are you asking if there is existing short/long test using cartesian STO?  I don't think there's any existing test with this combination.

2023-11-17 22:52 UTC, ye-luo commented
> Are you asking if there is existing short/long test using cartesian STO? I don't think there's any existing test with this combination.

Any test deterministic/short/long tests? I'm wondering if you find the issue when running something or you just noticed it as you read the code.

2023-11-20 20:54 UTC, ye-luo requested changes
It is good to catch the missing case but unit test needs improvement to make actual checks. See my comments in source.

2023-11-20 20:54 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +     <basisset keyword="STO" transform="no">
Currently `transform` is read from the `sposet_collection` level instead of `basisset`.

2023-11-20 20:54 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +  LCAOrbitalBuilder lcaob_sto_cart = LCAOrbitalBuilder(elec, ions, c, doc.getRoot());
It is less clear to me if this way of writing involves both constructor and copy constructor.
Prefer
```
LCAOrbitalBuilder lcaob_sto_cart(elec, ions, c, doc.getRoot());
```

2023-11-20 20:54 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +
To make these test solid. Please add a basisset accessor to LCAOrbitalBuilder and test the actual basisset class via dynamic_cast.

2023-11-21 22:32 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +#include "LCAO/LCAOrbitalBuilder.cpp"
Including a cpp file?

2023-11-21 23:47 UTC, markdewing commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +#include "LCAO/LCAOrbitalBuilder.cpp"
D'oh!  How'd that sneak in there????

2023-11-23 03:59 UTC, ye-luo commented on src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp
> +     <basisset keyword="STO" transform="no">
I was wrong. `transform` is read as an `basisset` attribute.

2023-11-23 03:59 UTC, ye-luo approved these changes
LGTM

2023-11-23 04:00 UTC, ye-luo commented
Test this please

2023-11-27 17:04 UTC, prckent approved these changes
I'll note that while this improves both the design and testing situation, I think we are still short on numerical correctness unit tests in LCAO.

2023-11-27 17:04 UTC, merged