Call cheaper TrialWaveFunction::mw_evaluateParameterDerivativesWF in SR
QMCPACK/qmcpack pull request #5163
Opened 2024-09-12 22:51 UTC by ye-luo

## Proposed changes
SR doesn't need derivatives from KE. so introduce and call `TrialWaveFunction::mw_evaluateParameterDerivativesWF`.
`WFC::mw_evaluateParameterDerivativesWF` exists, I just need to expose it at the TWF level.

## What type(s) of changes does this code introduce?
- New feature
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

2024-09-12 23:37 UTC, camelto2 submitted a review, later dismissed

2024-09-12 23:41 UTC, prckent requested changes
More documentation around the function definition please. The WFC API needs to be very clearly documented otherwise it impedes implementing any new wavefunction component.

2024-09-13 14:43 UTC, prckent approved these changes

2024-09-13 14:43 UTC, prckent commented
Test this please

2024-09-13 15:53 UTC, merged