Nexus: fix job option usage at user level
QMCPACK/qmcpack pull request #5255
Opened 2024-12-16 16:13 UTC by jtkrogel

## Proposed changes

This PR improves job option handling in Nexus, making the interface often used at the Machine level available at the user level.

For example, to achieve what is desired in #5240, the following input can be used:

```
settings(
    pseudo_dir = './pseudopotentials',
    results    = '',
    sleep      = 3,
    machine    = 'ws16',
    )

...

scf = generate_pwscf(
    job = job(cores=16,app='pw.x',run_options=dict(bind_to='--bind-to none')),
    ...
    )

...
```

This results in a call to mpirun like:

```
      Executing:  
        export OMP_NUM_THREADS=1
        mpirun --bind-to none -np 16 pw.x -input scf.in 
```

All current tests pass.

## What type(s) of changes does this code introduce?

- Bugfix
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

2024-12-16 16:21 UTC, prckent commented
Thanks Jaron.

1. Is it possible to specify these options at a higher level still? Likely every job run on a specific machine+set of software will need the same options. We don't want users to have to modify their Nexus scripts on a per machine level except at the top.
3. Can you update the Nexus documentation to describe these options?

2024-12-16 17:00 UTC, jtkrogel commented
Option (+other) data can be shared at the top of the Nexus file.  This is often how large scripts are handled, and/or ones meant to run on multiple machines.

Here is an example of three pwscf jobs across two machines that share software and runtime/submission options:
```
settings(
    pseudo_dir = './pseudopotentials',
    results    = '',
    sleep      = 3,
    machine    = 'ws128',
    )

if settings.machine=='ws128':
    # jobs for 128 core workstation
    scf_opts1 = obj(app         = 'pw.x',
                    run_options = '--bind-to none')
    scf_opts2 = obj(app         = 'pw.x',
                    run_options = '--bind-to none',
                    app_options = '-nk 8')
    scf_job1 = job(cores= 64,**scf_opts1)
    scf_job2 = job(cores= 64,**scf_opts2)
    scf_job3 = job(cores=128,**scf_opts2)

elif settings.machine=='inti':
    # jobs for "Inti" cluster
    qe_presub = '''
module purge
module load mpi/openmpi-x86_64  
module load qe/quantum-espresso 
'''
    scf_opts1 = obj(nodes       = 1,
                    hours       = 1,
                    app         = 'pw.x',
                    run_options = '--bind-to none',
                    presub      = qe_presub)
    scf_opts2 = obj(nodes       = 1,
                    hours       = 1,
                    app         = 'pw.x',
                    run_options = '--bind-to none',
                    app_options = '-nk 8',
                    presub      = qe_presub)
    scf_job1 = job(processes_per_node=64,**scf_opts1)
    scf_job2 = job(processes_per_node=64,**scf_opts2)
    scf_job3 = job(**scf_opts2)

else:
    print('machine unknown!')
    exit()
#end if
```

2024-12-16 21:32 UTC, ye-luo approved these changes

2024-12-16 21:32 UTC, ye-luo commented
Test this please

2024-12-16 21:33 UTC, ye-luo commented
Does this PR fix the CI failure in https://github.com/QMCPACK/qmcpack/pull/5240?

2024-12-16 21:43 UTC, jtkrogel commented
This PR should not cause the CI to fail.  Nexus behaves in the same way as before (and all tests pass).  

Instead, it should open the way to allow usage of flags to mpirun as needed per machine environment.

2024-12-16 21:53 UTC, prckent commented
I would like to request documentation is added.

I am concerned at the relative rate of growth of Nexus functionality vs growth of the documentation.

2025-03-19 20:44 UTC, ye-luo requested changes
Please address documentation request https://github.com/QMCPACK/qmcpack/pull/5255#issuecomment-2546901276

2025-04-02 17:55 UTC, prckent commented
I have added the requested documentation in a separate PR #5413 .

2025-04-02 17:57 UTC, prckent approved these changes

2025-04-02 17:57 UTC, prckent commented
Test this please

2025-04-02 19:34 UTC, ye-luo commented
Test this please

2025-04-02 19:35 UTC, ye-luo approved these changes

2025-04-02 20:27 UTC, merged