Add timer for walker log
QMCPACK/qmcpack pull request #5259
Opened 2024-12-26 23:14 UTC by PDoakORNL

## Proposed changes

I was curious about the cost of walker logging so I added a timer.  
Running the batched energy density with it on its 100 times more expensive than the energy denisty but still just ~15% of the total dmc time. 
This is wth 2400 walkers across 8 ranks with 3 crowds each. 8 v100's
diamond 1x1x1

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
dgx server

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

2024-12-27 00:30 UTC, ye-luo reviewed
This PR adds only 1 walker_log timer covers all kinds of walker_log operations. Only the total time can be interpreted and time per call is not really meaningful.
Could you put fine timers into functions of WalkerLogCollector and WalkerLogManager? In this way, we will have better timer resolution and zero timer impact if walker_log is not activated.

2024-12-27 17:06 UTC, PDoakORNL commented
The timer gets listed in different enclosing timer scopes in the output.  It's quite easy to tell what is what from the number of calls for each timer output.  But I get what you mean, will do when I have time.

2024-12-30 18:08 UTC, prckent requested changes
Agreeing with Ye's suggestions: Better to have the logging within the log manager etc. Also nicer to have finer timers in case any one operation is particularly slow.

2025-02-07 17:17 UTC, prckent requested changes
Very minor nit, but it looks like clangformat needs to be rerun on at least WalkerLogCollector.cpp

2025-02-07 20:47 UTC, prckent approved these changes
LGTM but note I have not run it.

2025-02-07 21:06 UTC, ye-luo commented on src/QMCDrivers/WalkerLogBuffer.cpp
> +
Do you mind move the remaining definition of collect functions to this cpp file?

2025-02-10 18:35 UTC, PDoakORNL commented on src/QMCDrivers/WalkerLogBuffer.h
> +  TimerList_t walker_log_buffer_timers_;
#5309

2025-02-10 18:44 UTC, ye-luo commented
Test this please

2025-02-10 18:45 UTC, ye-luo approved these changes

2025-02-10 20:52 UTC, merged