Remove 16 rank driver unit tests
QMCPACK/qmcpack pull request #5260
Opened 2024-12-30 18:37 UTC by prckent

## Proposed changes

Remove the 16 task driver unit tests, leaving the 1,2,3, and 4 way versions.

The 16 task tests are occasionally unreliable when run on single GPUs (e.g. via sulfur CI, and in bora nightlies) and do not add needed coverage in my opinion.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

None. CI should run and we should check the coverage.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

2024-12-30 18:38 UTC, prckent commented
Test this please

2024-12-31 18:58 UTC, ye-luo requested changes
Put this on hold. It is worth checking the cause of the failure. Likely it is caused by insufficient GPU memory when dealing with 48 walkers each with one cusolver handle.

2024-12-31 20:01 UTC, prckent commented
Example failures on bora https://cdash.qmcpack.org/testSummary.php?project=1&name=deterministic-unit_test_new_drivers_mpi-r16&date=2024-12-30

2025-01-10 15:08 UTC, ye-luo commented
The original issue has been resolved by #5265

2025-01-10 15:08 UTC, closed without merging